### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by lurudong** [Dark2017/react-dark-photo#1]
![image](https://user-images.githubusercontent.com/44517714/140860877-1aa8c8b8-d68a-4481-a43c-4418de34f9d6.png)
图片太大会把放大，缩小，旋转的工具看不见，能不能什么时候那些工具都显示出来，固定在一个位置 上

**Comment by lurudong** [comment]
![image](https://user-images.githubusercontent.com/44517714/140861049-9ee3888c-15e4-4e58-893f-80e309a0eeca.png)

**Comment by Dark2017** [comment]
已修复。安装最新版本即可。感谢您的反馈。

**Comment by lurudong** [comment]
好的，感谢.辛苦了
